{
 "title": "Portfolio Overview",
 "tags": [
  "portfolio",
  "blackbox",
  "synthetic-monitoring"
 ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Portfolio availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"portfolio_blackbox\"}"
    }
   ]
  },
  {
   "title": "HTTP status code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"portfolio_blackbox\"}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"portfolio_blackbox\"}",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Availability percentage - 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"portfolio_blackbox\"}[5m]) * 100",
     "legendFormat": "availability %"
    }
   ]
  }
 ]
}